# 1. Basic Matrix Algebra

Like vectors, matrices have their own set of algebraic operations. In this mission, we'll learn the core matrix operations and build up to using some of them to solve the matrix equation. Let's first start with matrix addition and subtraction.

If you recall from the previous mission, a matrix consists of one or more column vectors.

![](matrix_vector_decomposition.svg)

Because of that, the operations from vectors also carry over to matrices. We could perform vector addition and subtraction between vectors with the same number of rows. We can perform matrix addition and subtraction between matrices containing the same number of rows and columns.

![](valid_matrix_sums.svg)

As with vectors, matrix addition and subtraction works by distributing the operations across the specific elements and combining them.

![](matrix_addition.svg)

Lastly, we can also multiply a matrix by a scalar value, just like we can with a vector.

![](matrix_scalar_multiplication.svg)

Let's practice applying these operators using NumPy.


# 2. Matrix Vector Multiplication
The matrix equation we discussed briefly in the last mission is an example of matrix-vector multiplication. When we multiply a matrix by a vector, we are essentially **combining each row in the matrix with the column vector.**

![](matrix_vector_multiplication.svg)

To multiply a matrix by a vector, the number of columns in the matrix needs to match the number of rows in the vector.

![](valid_matrix_products.svg)

To multiply a matrix with a vector in NumPy, we need to use the numpy.dot() function.

In [38]:
import numpy as np

matrix_a = np.asarray([
    [0.7, 3, 9],
    [1.7, 2, 9],
    [0.7, 9, 2]
], dtype=np.float32)
print(matrix_a,'\n')

vector_b = np.asarray([
    [1], [2], [1]
], dtype=np.float32)
print(vector_b,'\n')

ab_product = np.dot(matrix_a, vector_b)

print(ab_product)

[[ 0.69999999  3.          9.        ]
 [ 1.70000005  2.          9.        ]
 [ 0.69999999  9.          2.        ]] 

[[ 1.]
 [ 2.]
 [ 1.]] 

[[ 15.69999981]
 [ 14.69999981]
 [ 20.70000076]]


# 3. Matrix Multiplication

Because a matrix consists of column vectors, we can extend what we learned about matrix vector multiplication to multiply matrices together. In matrix vector multiplication, we performed a dot product between each row in the matrix and the column vector. **In matrix multiplication, we extend this to perform a dot product between each row in the first matrix and each row in the second matrix.**

![](matrix_multiplication.svg)

As with matrix vector multiplication, the columns in the first matrix need to match the number of rows in the second matrix.

![](valid_matrix_multiplication.svg)

Note that the order of multiplication also matters.

![](matrix_multiplication.svg)

To multiply vectors in NumPy, we use the same numpy.dot() function we used in the last screen.

In [39]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

print(matrix_a,'\n')

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

print(matrix_b,'\n')

product_ab = np.dot(matrix_a, matrix_b)
product_ba = np.dot(matrix_b, matrix_a)

print(product_ab, '\n')
print(product_ba)

[[ 0.69999999  3.        ]
 [ 1.70000005  2.        ]
 [ 0.69999999  9.        ]] 

[[ 113.    3.   10.]
 [   1.    0.    1.]] 

[[  82.09999847    2.0999999    10.        ]
 [ 194.1000061     5.10000038   19.        ]
 [  88.09999847    2.0999999    16.        ]] 

[[  91.19999695  435.        ]
 [   1.39999998   12.        ]]


# 4. Transpose Matrix

The transpose of a matrix switches the rows and columns of a matrix. You can think of the transpose operation as a rotation. In data science, we're often working with data tables of different dimensions. Because of the requirements for matrix multiplication, we sometimes want to take the transpose of a matrix to allow us to multiply matrices together that, by default, don't overlap in number of rows and columns.

Here's what the transpose of a matrix looks like visually:

![](Matrix_transpose.gif)

Mathematically, we use the notation AT to specify the transpose operation.

$A^T + B^T = C$

The transpose has a few different interesting rules that are a bit intuitive. For example, when taking the transpose of the sum of two matrices, we can distribute the transpose operation to each matrix:

$(A+B)^T = A^T + B^T$

One counterintuitive rule is when we take the transpose of the product of 2 matrices:

$(AB)^T = B^TA^T$

Let's explore these properties using NumPy. To compute the transpose of a NumPy ndarray, we need to use the numpy.transpose() function.

In [40]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)


transpose_a = np.transpose(matrix_a)
print(np.transpose(transpose_a),'\n')

#A trans * B trans
trans_ab = np.dot(np.transpose(matrix_a), np.transpose(matrix_b))
print(trans_ab,'\n')

#B trans * A trans
trans_ba = np.dot(np.transpose(matrix_b), np.transpose(matrix_a))
print(trans_ba,'\n')

#A*B Transposed (should equal previous matrix!)
product_ab = np.dot(matrix_a, matrix_b)
print(np.transpose(product_ab),'\n')

[[ 0.69999999  3.        ]
 [ 1.70000005  2.        ]
 [ 0.69999999  9.        ]] 

[[  91.19999695    1.39999998]
 [ 435.           12.        ]] 

[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]] 

[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]] 



# 5. Identity Matrix
In the matrix equation that we discussed in the last mission, we're trying to solve for the vector x→.

$A\vec{x} = \vec{b}$

Right now, the matrix A multiplies the vector x→ and we need a way to cancel A.

Let's look at the identity matrix, which we touched on briefly at the end of the first mission in this course. If you recall, the identity matrix contains 1 along the diagonals and 0 elsewhere. Here's what the 2x2 identity matrix looks like, often represented symbolically using I2:

$I_2 = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

When we multiply I2 with any vector containing 2 elements, the resulting vector matches the original vector exactly:

$I_2 \vec{x} = \vec{x}$

This is because each element in the vector is multiplied exactly once by the diagonal 1 value in the identity matrix:

![](identity_matrix.svg)

**If we can transform matrix A and convert it into the identity matrix, then only the solution vector will remain $\vec{x}$.** Let's practice working with the identity matrix before exploring how to transform A into I.

We can create any In identity matrix using the numpy.identity() function. This function only has 1 required parameter, n, which specifies the n x n identity matrix we want

In [41]:
i_2 = np.identity(2)
i_3 = np.identity(3)

matrix_33 = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_23 = np.asarray([
    [0.7, 3, 1],
    [1.7, 2, 10],
], dtype=np.float32)

identity_33 = np.dot(i_3, matrix_33)
identity_23 = np.dot(i_2, matrix_23)

#We should expect identity_33 to match matrix_33 and identity_23 to match matrix_23.
print(identity_33)
print(identity_23)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[  0.69999999   3.           1.        ]
 [  1.70000005   2.          10.        ]]


# 6. Matrix Inverse

Now that we're more familiar with the identity matrix, let's discuss how to cancel the coefficient matrix A. Said another way, we want to transform A into the identity matrix I. Multiplying the inverse of a matrix by the matrix accomplishes this task.

The matrix inverse is similar to the idea of the multiplicative inverse. For example, let's say we want to solve for x in the equation 5x=10. To do so, we need to multiply both sides by the multiplicative inverse of 5, which is 5^−1 (or 1/5):

$5^{-1}*5x = 5^{-1}*10$

The inverse of 5 transforms it to 1 and leaves us with the solution: x=2. To solve for the vector x→ in the matrix equation, we need to multiply both sides by the inverse of A:

$A^{-1}A\vec{x} = A^{-1}\vec{b}$

This simplifies to $I\vec{x} = A^{-1}\vec{b}$ and we're then left with the formula for calculating the solution vector:

$\vec{x} = A^{-1}\vec{b}$

While we use the matrix inverse to cancel out specific terms in the same fashion as the multiplicative inverse, the calculation is completely different. Let's understand the calculation for the inverse of a 2x2 matrix.

If $A =  \begin{bmatrix} a & b \\ c & d \end{bmatrix}$ then $A^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$.

The term **ad−bc** is known as **the determinant** and is often written as $det(A) = ad - bc$ or as $|A| = ad - bc$. **Because we're dividing by the determinant when calculating the matrix inverse, a 2 x 2 matrix is only invertible if the determinant is not equal to 0**. In this step and the next step, we'll focus on finding the matrix inverse when A is a 2 x 2 matrix. Later in this mission, we'll walkthrough how to compute the matrix inverse for a higher dimensional matrix (3 x 3 and greater).

Let's implement the matrix inverse in Python before moving on to solving the matrix equation.

**Instructions**

- Create a function named matrix_inverse_two() that accepts a 2 x 2 matrix, as a NumPy ndarray, and returns the matrix inverse.This function should first calculate the determinant of the matrix.
  - If the determinant is equal to 0, an error should be returned.
  - If the determinant is not equal to 0, this function should return the matrix inverse.
- Calculate the inverse of matrix_a using the function you just wrote and assign the result to inverse_a.
- Multiply inverse_a with matrix_a and assign the result to i_2. Display i_2 using the print() function.

In [42]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
# create function that returns invesrse of matrix
def matrix_inverse_two(mat):
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    if det == 0:
        raise ValueError("The matrix isn't invertible")
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    inv_mat = np.dot(1/det, right_mat)
    return inv_mat

inverse_a = matrix_inverse_two(matrix_a)

i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[ 1.  0.]
 [ 0.  1.]]


# 7. Solving The Matrix Equation
Now that we know how to compute the matrix inverse, we can solve our system using the matrix equation $A\vec{x} = \vec{b}$:

$\left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right] \begin{bmatrix} x_1\\ x_2 \end{bmatrix} =  \begin{bmatrix} -1000\\ -100 \end{bmatrix}$

We start by left multiplying A^−1 on both sides:

$\left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right]^{-1} \left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right] \begin{bmatrix} x_1\\ x_2 \end{bmatrix} =  \left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right]^{-1} \begin{bmatrix} -1000\\ -100 \end{bmatrix}$

This simplifies to:

$\begin{bmatrix} x_1\\ x_2 \end{bmatrix} =  \left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right]^{-1} \begin{bmatrix} -1000\\ -100 \end{bmatrix}$

Let's finish this last step in Python. To compute the inverse of a NumPy ndarray, we need to use the numpy.linalg.inv() function.


In [43]:
matrix_a = np.asarray([
    [30, -1],
    [50, -1]
])

vector_b = np.asarray([
    [-1000],
    [-100]
])

#use the np.linalg.inv function to do this!!!
matrix_a_inverse = np.linalg.inv(matrix_a)
solution_x = np.dot(matrix_a_inverse, vector_b)
print(solution_x)

[[   45.]
 [ 2350.]]


# 8. Determinant for Higher Dimensions

Before we discuss how to compute the matrix inverse for higher dimensional matrices, let's dive deeper into the determinant and introduce some more terminology. So far, we've mostly worked with matrices that contain the same number orws and columns. These matrices are known as square matrices and we can only compute the determinant and matrix inverse for square matrices. In addition, **we can only compute the matrix inverse of a square matrix when the determinant is not equal to 0.** (ONLY A SQUARE!?!? REALLY?!?! SO HOW USEFUL IS THIS TECHNIQUE?!?! I DONT REALLY KNOW YET TBH...)

To find the determinant of a higher dimensional square matrix, we need use the more general form of the determinant. Here's what that looks like:

![](3d_determinant_one.svg)

The determinant of a higher-dimensional system involves breaking down the full matrix into **minor matrices.** First, we select a row or column (most teaching materials select the first row). For the first value in that row, we "hide" the other values in that row (2nd and 3rd value in the row) and in that column (2nd and 3rd value in the column), select the rest of the elements as the minor matrix, and multiply the scalar value with the determinant of the minor matrix. We repeat this for the remaining values in the first row. This diagram helps illustrate this much clearer:

![](3d_determinant_two.svg)

Here's a concrete example:

![](3d_determinant_three.svg)

To compute the determinant in NumPy, we use the *numpy.linalg.det()* function. We'll leave it to you to read the documentation and learn how to use this function.

*ALSO REMEMBER THAT WHEN YOU MULTIPLE THE MINOR MATRICES BY A, B, or C, YOU HAVE TO CHANGE THEIR SIGNS TO MATCH THE FOLLOWING:*
![](POST_NEG.jpg)

In [57]:
matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])

matrix_33 = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
det_22 = np.linalg.det(matrix_22)
det_33 = np.linalg.det(matrix_33)

print(det_22)
print(det_33)

matrix_22*matrix_22

0.0
-9.51619735393e-16


array([[64, 16],
       [16,  4]])

# 9. Matrix Inverse for Higher Dimensions
To calculate the matrix inverse for a 3 by 3, or larger, matrix, we need to also work with the more general form of the matrix inverse equation. Similar to the determinant for higher-dimensional matrices, the matrix inverse works by generating minor matrices that are dependent on the position in the matrix. Here's a diagram describing the matrix inverse for a 3 by 3 matrix:

![](3d_matrix_inverse.svg)

While it's helpful to know how to compute the inverse this way for higher dimensional matrices, the amount of careful arithmetic you have to by hand is large. Thankfully, the numpy.linalg.inv() function can work with any n-dimensional square matrix.


**THIS IS A PRETTY SIMPLE, BUT METICULOUS PROCESS. THIS SITE HAS SOME GREAT EXAMPLES. You probably just need to get the basic process, because software will do this for you very quickly (as seen below!)**

https://www.mathsisfun.com/algebra/matrix-inverse-minors-cofactors-adjugate.html
![](matrix-gauss-jordan3.gif)
*above is the original matrix
![](matrix-minors2.svg)
*This is the determinents of all the 'minor matrices'
![](matrix-adjugate-inverse.SVG)
*Ten is the determinant of A

In [68]:
matrix_a = np.asarray([
    [3,0,2],
    [2,0,-2],
    [0,1,1]
])

#use the inverse formula to calucalte
matrix_a_inverse = np.linalg.inv(matrix_a)
print(matrix_a_inverse,'\n')

print('LOOK! IT SHOULD PRODUCE THE EXACT SAME MATRIX FROM THE EXAMPLE ABOVE')

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3  0. ]] 

LOOK! IT SHOULD PRODUCE THE EXACT SAME MATRIX FROM THE EXAMPLE ABOVE


# 10. Next Steps

In this mission, we learned about the different matrix operations and how to solve a linear system that's represented using the matrix equation using the matrix inverse. In the next mission, we'll learn the different ways a solution set can be represented and how to calculate the determinant of a higher dimensional matrix.